### ISSUE TITLE
Some labels missing in statistic view

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#10]
Some mouse-over labels are not shown in the statistics view. (e.g. Vogelbeere)

**Comment by rawyler** [comment]
Missing mouse-over means something with the data is missing there. I think I saw this with MeteoSchweiz data only.

**Comment by pgoellnitz** [comment]
`ERROR TypeError: Cannot read property 'name_de' of undefined`

yes, looks like we might be missing some descriptions. Didn't look any deeper yet.

**Comment by pgoellnitz** [comment]
For 'meteoswiss only' species the phenophase definition is missing and needs to be provided by Globe (@daria-sl) and configured in the app.

**Comment by daria-sl** [comment]
Test successful. Renaming of "Wiesenschaumkraut" and "Wiesenlöwenzahn" is now fine, too. Thanks @pgoellnitz !
