### ISSUE TITLE
Translations are incomplete in Dropdown for French and Italian

### ISSUE THREAD

**Issue by daria-sl** [globe-swiss/phaenonet-client#105]
When using the dropdown for species (both on the map and on the statistics view), Wiesenschaumkraut and Wiesenlöwenzahn are not displayed in the respective language, but always in German:

![grafik](https://user-images.githubusercontent.com/65400300/105333815-72146400-5bd6-11eb-9b30-aa804f05f569.png)

However, the translations are available in the application ON the analysis images:

![grafik](https://user-images.githubusercontent.com/65400300/105333925-8f493280-5bd6-11eb-9af4-00f937adae7e.png)

**Comment by pgoellnitz** [comment]
also rename species in fr:
old: Bouleau / new: Bouleau pendant

**Comment by daria-sl** [comment]
Test successful! Thank you @pgoellnitz :)
