### ISSUE TITLE
Validate email address on register form

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#12]
The register form should validate the email address and mark the field as invalid and deactivate the submit button.

**Comment by pgoellnitz** [comment]
Added basic validation of the email address and more specific error messages when registering.

**Comment by daria-sl** [comment]
"auth/invalid-email.title": | "Ungültige Mailadresse" | "Adresse courriel non valable" | "Indirizzo e-mail non valido"

"auth/invalid-email.message": | "Die eingegebene Mailadresse ist ungültig." | "L'adresse courriel saisie n'est pas valable." | "L'indirizzo e-mail inserito non è valido."

"auth/email-already-in-use.title": | "Mailadresse bereits verwendet" | "Adresse courriel déjà utilisée" | "Indirizzo e-mail già usato"

"auth/email-already-in-use.message": | "Die eingegebene Mailadresse wird bereits verwendet." | "L'adresse courriel saisie est déjà utilisée." | "L'indirizzo e-mail inserito è già usato."

**Comment by daria-sl** [comment]
The test (for all three languages identically) showed two issues that should be improved:

1) there are different ways of warnings:
(A) The erroneous field is highlighted in red and the warning is shown inline (registration button is not clickable):
![image](https://user-images.githubusercontent.com/65400300/83241108-a3997480-a19a-11ea-96a8-3eeaf9404e39.png)
(B) Registration button is clickable, warning is shown after pressing "Registration" in a pop-up window:
![image](https://user-images.githubusercontent.com/65400300/83241181-c3309d00-a19a-11ea-96a7-02ff18314823.png)
I would suggest to unify/standardize the warning method, preferably to method (A).

2) The "Mailadresse ist ungültig"-warning is not shown. When entering an email without "@", the field is highlighted in red, the registration button is not clickable, but no warning is shown:
![image](https://user-images.githubusercontent.com/65400300/83241430-1dc9f900-a19b-11ea-9059-debf55cf493e.png)
The warning should be shown - preferably inline with method (A).

**Comment by daria-sl** [comment]
Ciao Philippe

Ich würde das gerne am Freitag an unserem Meeting besprechen =) ... zusätzlich zum Objekt löschen (Mail von Dani) und den Änderungen in den Aktivitäten-Feeds.

Liebe Grüsse,
Daria

Daria Lehmann
Wissenschaftliche Mitarbeiterin

[cid:image001.png@01D638FC.4CDA7E70]

Verein GLOBE Schweiz
Papiermühlestrasse 172
3003 Bern

Tel.: +41 58 484 96 41<tel:+41%2058%20484%2096%2041>
E-Mail: dlehmann@globe-swiss.ch<mailto:dlehmann@globe-swiss.ch>
Web: www.globe-swiss.ch<http://www.globe-swiss.ch> | www.phaenonet.ch<http://www.phaenonet.ch>

Von: Philippe Göllnitz <notifications@github.com>
Gesendet: Freitag, 29. Mai 2020 18:53
An: globe-swiss/phaenonet-client <phaenonet-client@noreply.github.com>
Cc: Daria Lehmann <dlehmann@globe-swiss.ch>; Comment <comment@noreply.github.com>
Betreff: Re: [globe-swiss/phaenonet-client] Validate email address on register form (#12)


Just to understand these errors are two different things. (A) is client side validation errors (B) are messages reacting to server side errors. Server side errors are only evaluated after you submit the form.

What could be done with some effort is:

  *   Display the warning message you mentioned in (2)
  *   use a more narrow email filter (now using the default one just checking for @)
  *   change the way server side errors are displayed (also impacts login screen)

**Comment by pgoellnitz** [comment]
Only set "Die eingegebene Mailadresse ist ungültig." as inline warning.

**Comment by daria-sl** [comment]
test successful
