### ISSUE TITLE
Registering a new account is confirmed twice

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#13]
The confirmation 'popup' for the registration is shown twice (after some seconds).

**Comment by pgoellnitz** [comment]
Triggers because cloud functions update creation and modification dates on the user. Needs to be set to only subscribe to the first event.

**Comment by pgoellnitz** [comment]
Also multiple subscriptions are created when registration fails.

**Comment by daria-sl** [comment]
test successful
