### ISSUE TITLE
prevent double inserts on individuals

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#130]
Database shows quite some duplicate individuals, inserted shortly after another.

Reproduce: Click insert button multiple times before the page refreshes

- Button could be disabled (for some time) after being pressed
- could pre-generate the id to avoid multiple inserts

**Comment by pgoellnitz** [comment]
opted for disabling button with spinner on top:
![image](https://user-images.githubusercontent.com/17765935/108499847-393bdd80-72af-11eb-890c-86cbd8a13af7.png)

@daria-sl, wdyt? Works all good for me, could you check with some of your devices (especially ios)?

**Comment by pgoellnitz** [comment]
Error handling is (and always was) missing.
E.g. uploading file that is not an image, too big, etc.

**Comment by pgoellnitz** [comment]
Fixed navigation on error and adding a toast-alert message.

@daria-sl: Can you send me the text fragments to be used for the error? We need a **title**, **message** and corresponding **translations**.
Or we can just use a generic message for now and push further effort to #102.

**Comment by daria-sl** [comment]
> 
> 
> opted for disabling button with spinner on top:
> ![image](https://user-images.githubusercontent.com/17765935/108499847-393bdd80-72af-11eb-890c-86cbd8a13af7.png)
> 
> @daria-sl, wdyt? Works all good for me, could you check with some of your devices (especially ios)?
> 
> https://phaenonet-test--refs-heads-130-dbl-insert-8mhat5g6.web.app

YES, very good solution and working on IOS, too. What I thought: maybe now that we have this functionality, why not let the spinner spin some more time, until we could correctly load the image of the object, so when I add an object with picture, I can see it from the beginning...? But maybe this thought is unneccessary and I am mixing up things that do not belong together from a technical point of view!

**Comment by daria-sl** [comment]
> 
> 
> Fixed navigation on error and adding a toast-alert message.
> 
> @daria-sl: Can you send me the text fragments to be used for the error? We need a **title**, **message** and corresponding **translations**.
> Or we can just use a generic message for now and push further effort to #102.

@pgoellnitz I do not quite understand where this message would be displayed. When adding an object and a picture with unsupported format type, would it show after I saved the image only? Why not let it display in red text right in the "image-field"? Then we would only need a text and no title of the error...

**Comment by pgoellnitz** [comment]
> YES, very good solution and working on IOS, too. What I thought: maybe now that we have this functionality, why not let the spinner spin some more time, until we could correctly load the image of the object, so when I add an object with picture, I can see it from the beginning...? But maybe this thought is unnecessary and I am mixing up things that do not belong together from a technical point of view!

There are definitely things we can do there but currently we don't know when the image is processed in the backend as it is done asynchronously. -> #102 

> @pgoellnitz I do not quite understand where this message would be displayed. When adding an object and a picture with unsupported format type, would it show after I saved the image only? Why not let it display in red text right in the "image-field"? Then we would only need a text and no title of the error...

I think we can improve the image validation in the UI (-> #102), however we still need to respond if the backend rejects the image (for any reason, size and type are the ones that come to mind).
The message is displayed as a _toast_. You can try it out yourself if you upload a text file e.g.

![image](https://user-images.githubusercontent.com/17765935/108740973-867db080-7536-11eb-9d80-a2a3bfb69d93.png)

**Comment by daria-sl** [comment]
okay, I see, thank you for the clarification! Here goes my proposition for the texts:

Deutsch | Französisch | Italienisch
-- | -- | --
Fehlerhaftes Foto | Photo erronée | Foto errata
Das Foto konnte nicht hochgeladen werden. Das Format wird nicht unterstützt oder die maximale Grösse wurde überschritten. | La photo n'a pas pu être téléchargée. Le format n'est pas supporté ou la taille maximale a été dépassée. | La foto non può essere caricata. Il formato non è supportato o la dimensione massima è stata superata.
