### ISSUE TITLE
Invites part II: subdivision and order

### ISSUE THREAD

**Issue by daria-sl** [globe-swiss/phaenonet-client#145]
On the page "Einladungen", the accepted invitations should be separated from the open ones (subtitles on the left: "OFFENE EINLADUNGEN" / "ANGENOMMENE EINLADUNGEN"). Open invitations are displayed first, followed by accepted ones. Each of the two lists is then ordered by date; for open invitations, the date of the last invitation sent is considered (newer dates are displayed first), for accepted invitation, the date of registration of the user is considered (newer dates are displayed first).

**Comment by pgoellnitz** [comment]
Hi @EstMed,
I did the changes to split and order the lists but made some assumptions in the design regarding the "no invite screen" and button placement.

You can check the result in the test environment [here](https://phaenonet-test--refs-heads-145-invite-divide-order-m9a4rwf8.web.app) [expires 2022-01-21 17:20:36]

If ok for you I would need the translations for the new "subtitles" daria-sl defined in the ticket.

**Comment by EstMed** [comment]
Hi @pgoellnitz 
I was too late for the test environment.
the translations are INVITATIONS OUVERTES / INVITATIONS ACCEPTEES and INVITI APERTI / INVITI ACCETTATI.

**Comment by pgoellnitz** [comment]
Thanks for the translations.
Here you go again: https://phaenonet-test--refs-heads-145-invite-divide-order-wgtgxht3.web.app

**Comment by EstMed** [comment]
Ok great!

**Comment by EstMed** [comment]
👍
