### ISSUE TITLE
'Add Individual' button is not shown for newly registered users

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#15]
After registration of a new account the '+ Individual' button is not shown on the map screen.

**Comment by pgoellnitz** [comment]
First time the map is loaded the user might not be logged in yet and the login state is cached on page load from local storage.
Checking the local storage directly seems to draw quite some computation time and might not be a good solution.

Alternatively we could show the button at all times and forward to the login screen.

**Comment by daria-sl** [comment]
I think the solution you are proposing with always showing the button and then, when it is clicked and the user is not logged in, forward to the login screen, is very good 👍

**Comment by daria-sl** [comment]
@pgoellnitz this is perfect, thank you!
