### ISSUE TITLE
Opening registration page when already logged in shows confusing message

### ISSUE THREAD

**Issue by daria-sl** [globe-swiss/phaenonet-client#150]
When opening directly the registration page: If you are already logged in it redirects to the map, with a confusing message that you were "registered successfully".

This message should be changed (texts d f it @daria-sl tbd) and the redirection should rather be to the profile page so the user can see very clearly that he/she is already logged in.

**Comment by pgoellnitz** [comment]
I don't think we need any text here and should directly forward to the default view (map or profile).

**Comment by daria-sl** [comment]
okay, let's do this and redirect to the profile. thank you!

**Comment by pgoellnitz** [comment]
duplicate on https://github.com/globe-swiss/phaenonet-client/issues/125
