### ISSUE TITLE
Allow to cancel entering observation date

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#16]
As a user I would like to cancel the input of an observation date if I accidentally clicked on a wrong phenophase. E.g. by realizing that the description of the phenophase does not match the observation.

Currently it is possible by clicking outside of the dialog. It would be more intuitive to display a 'cancel' button.
Also, if clicked outside of the dialog, the value is shown in the observation form but not saved in the database.

**Comment by daria-sl** [comment]
This concerns also the "modify email address" and the "change password" window (under "edit profile").

**Comment by daria-sl** [comment]
is discussed in issue https://github.com/globe-swiss/phaenonet-client/issues/161
