### ISSUE TITLE
SUBISSUE: Hide metadata of object on small screens

### ISSUE THREAD

**Issue by daria-sl** [globe-swiss/phaenonet-client#165]
THIS IS A SUBISSUE OF ISSUE https://github.com/globe-swiss/phaenonet-client/issues/147

To keep things more simple and to show directly the more interesting information, on smaller screens, the object metadata should be hidden behind a "questionmark-symbol". It is only relevant on small screens, because on larger screens, object metadata is displayed in column right (but this column is moved on top of column on the left from screen sizes smaller than 1160 px width, cf. issue https://github.com/globe-swiss/phaenonet-client/issues/162).

example on public object view (only to show questionmark symbol and its placement, ignore rest)
![grafik](https://user-images.githubusercontent.com/65400300/121877086-8afaee80-cd0a-11eb-8669-46b90be521c2.png)

what is shown when questionmark-symbol is clicked on:
![grafik](https://user-images.githubusercontent.com/65400300/121877176-a2d27280-cd0a-11eb-8b53-d6f7a95ef840.png)
Text for title: "Informationen" - "Informations" - "Informazioni" (German, French, Italian)

**Comment by pgoellnitz** [comment]
hiding the info box implemented in https://github.com/globe-swiss/phaenonet-client/pull/475
