### ISSUE TITLE
SUBISSUE: Change workflow/dialogue of deleting observation

### ISSUE THREAD

**Issue by daria-sl** [globe-swiss/phaenonet-client#166]
- delete trash-symbol on object view (only edit symbol is left!)
![grafik](https://user-images.githubusercontent.com/65400300/121901771-f783e680-cd26-11eb-8b80-329e30799acd.png)

- when edit-symbol is clicked on, the following dialogue is shown (now with a red cross at the date-line; delete calendar symbol)
![grafik](https://user-images.githubusercontent.com/65400300/121878671-47a17f80-cd0c-11eb-9011-089642171879.png)

- if the date is clicked on, the caldenar opens (to edit the date). If the date is deleted, "jjjj-mm-dd" (or, alternatively, a calendar symbol) will appear on the line instead of the date. Deleting the date automatically removes the comment (if provided), too. If the date is deleted in the dialogue, but then the cross at the top right edge of the dialogue is clicked to close the dialogue, no changes are saved (still, the same date is entered as prior to opening the dialogue).

- if no observation has been entered yet and the green PLUS-symbol was clicked to add one, the dialogue looks as follows (calendar opens, once "jjjj-mm-dd" was clicked on):
![grafik](https://user-images.githubusercontent.com/65400300/121878832-74ee2d80-cd0c-11eb-8bf4-c08c85bd0cef.png)

**Comment by fabianpage** [comment]
As the behaviour of having the red cross at the end of the line is not directly supported by angular material i chaanged the delete to a secondary button like bellow:
<img width="646" alt="CleanShot 2022-04-07 at 14 52 38@2x" src="https://user-images.githubusercontent.com/8473/162203404-c57a958c-d435-4fa9-9633-ba1a6efe3294.png">

**Comment by EstMed** [comment]
When clicking the cross at the right upper corner any date that has been entered and saved before is deleted. 
It should not be delete but the action aborted without change.
