### ISSUE TITLE
Sort dropdowns alphabetically in all languages

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#17]
When creating a new individual the dropdowns should be ordered alphabetically depending on the language.
Especially for the selection of the species as this is a longer list.

from #94:
Species dropdowns should be ordered alphabetically per language. Species dropdowns occur at the following places in the application:

- add new object
- filter on map view
- filter on statistics view

**Comment by EstMed** [comment]
Great that it issorted differently in the different languages!
A next logical step would be that only the species that are recorded in a project appear when that project is selected. But let's tackle that after the design adaptation.
