### ISSUE TITLE
Introduce PhenoRanger Icon incl. information when clicked on icon

### ISSUE THREAD

**Issue by daria-sl** [globe-swiss/phaenonet-client#174]
Add PhenoRanger Icon (for flagged users) in
- personal profile view
![grafik](https://user-images.githubusercontent.com/65400300/131126418-0505549b-aa55-44fa-9405-34f82f43cc1b.png)

- public profile view

- public object view
![grafik](https://user-images.githubusercontent.com/65400300/131126686-dd98f938-df29-4202-bc8d-3c0faadd4229.png)

Add pop-up when PhenoRanger Icon is clicked on (both on public profile view and on public object view):
![grafik](https://user-images.githubusercontent.com/65400300/131126782-c52b8326-da13-48f3-974f-7cb30f3590d7.png)

Necessary information:
- [x] PhenoRanger Icon @daria-sl 
- [x] Texts for pop-up are to be defined @daria-sl

**Comment by daria-sl** [comment]
> 
> 
> @daria-sl, wouldn't it make sense to do the same thing for MeteoSwiss to keep things consistent?

good thought. However, there are two major differences between PhenoRanger and MeteoSwiss: 1) for MeteoSwiss it would only concern the public object view, as there is no private or public profile view. 2) the map icons for MeteoSwiss are distinct to those from PhaenoNet (so the difference is obvious already when looking at the map). Nevertheless, it would be nice to add an icon next to "MeteoSwiss" in the public object view, with additional information - especially, since MeteoSwiss is always looking for voluntary observers.

What do you think, should we prioritize this (Dani would need to design the icon and I would have to check with MeteoSwiss about the information sentence to be displayed) or should we create an additional issue and postpone it, as it does not directly influence our tasks for WSL?

**Comment by daria-sl** [comment]
Texts for pop-up:

GERMAN: PhenoRanger sind speziell ausgebildete Personen, welche Daten zu zusätzlichen Arten erfassen können. Für weitere Informationen, oder um selbst PhenoRanger zu werden, wenden Sie sich an pheno.rangers@wsl.ch.

FRENCH: Les PhenoRangers sont des personnes spécialement formées qui peuvent collecter des données sur des espèces supplémentaires. Pour plus d'informations, ou pour devenir vous-même un PhenoRanger, contactez pheno.rangers@wsl.ch.

ITALIAN: I PhenoRangers sono persone appositamente formate per raccogliere dati su specie supplementari. Per maggiori informazioni, o per diventare PhenoRanger, si prega di scrivere a pheno.rangers@wsl.ch.

**Comment by pgoellnitz** [comment]
Actually I don't see this one as a priority either. In my opinion, if we want introduce a badge for users, we should think a bit how we want to use it rather than just solve a tiny problem that lays in front of us.

**Comment by daria-sl** [comment]
I think we need to implement this ranger icon until spring so users will not get confused - also we promised it to WSL. We can still think more about badges and MeteoSwiss-Pop-up etc. after the first steps for PhenoRangers (add icon with information, add minimum of new species, think about filters on map and in statistics). I want to prevent normal PhaenoNet users from getting confused when they see data of species on the map to which they cannot add an observation themselves - with the icon in the profile of PhenoRangers we provide an explanation therefore.

**Comment by daria-sl** [comment]
@pgoellnitz I sent you a concept of PhaenoNet badges. Hope this helps so you can better implement the PhenoRangers icon in the application :)
