### ISSUE TITLE
Change "bourgeonnement" to "débourrement"

### ISSUE THREAD

**Issue by daria-sl** [globe-swiss/phaenonet-client#176]
We realized that this term in French is not scientifically correct. So it should be replaced everywhere in the App.

Old | New
-- | --
bourgeonnement | débourrement
Bourgeonnement | Débourrement
BOURGEONNEMENT | DÉBOURREMENT

@pgoellnitz could you please do this asap (as it is important that the instructions match the app) and tell me when it's done? Thx a lot :)

**Comment by pgoellnitz** [comment]
@daria-sl see changes here: https://github.com/globe-swiss/phaenonet-client/pull/179/files

I could find no matches for "BOURGEONNEMENT".
