### ISSUE TITLE
Error 404 Page

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#20]
The 404 error page just shows placeholder text.

**Comment by pgoellnitz** [comment]
related to #57

**Comment by daria-sl** [comment]
This draft is based on the page we have for signing in (no new elements were used). The e-mail should be clickable ("mailto:info@phaenonet.ch") and colored in any blue tone you like (maybe there is a standard?). Translations will follow asap.

![leere seite phaenonet](https://user-images.githubusercontent.com/65400300/98385893-d439e000-204f-11eb-95fe-2edd6564af17.jpg)

**Comment by daria-sl** [comment]
Here go the translations:

Deutsch | Französisch | Italienisch
-- | -- | --
Hier ist etwas schiefgelaufen. | Quelque chose a mal tourné. | Qualcosa non ha funzionato.
Diese Seite existiert leider nicht. Wenn Sie den Fehler melden möchten oder Hilfe benötigen, wenden Sie sich bitte an info@phaenonet.ch. | Cette page n’existe pas. Pour signaler cette erreur ou demander de l’aide, contactez info@phaenonet.ch. | Questa pagina non esiste. Per segnalare questo errore o chiedere aiuto, contattare info@phaenonet.ch.
zurück zur Karte | retour à la carte | indietro alla carta

**Comment by pgoellnitz** [comment]
Hi @daria-sl, thanks. We still need the page title w/ translations.

**Comment by daria-sl** [comment]
Here go the page titles in German - French - Italian:

Fehler - Erreur - Errore
