### ISSUE TITLE
Disallow forward slashes in nicknames 

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#208]
Forward slashes must be disallowed as nicknames are used as document id in Firestore.

- [x] check/repair uses with forward slashes
- [x] add errormessage + translations

**Comment by pgoellnitz** [comment]
Hi @daria-sl,
can you provide the translation for a new error message:
`Der Nickname enthält ungültige Zeichen.`

Thanks

**Comment by daria-sl** [comment]
ITALIAN: Il nome utente contiene caratteri non validi.
FRENCH: Le pseudo contient des caractères non valides.
