### ISSUE TITLE
Individuals w/o observations are not shown in public profile

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#23]
Individuals without observations are not shown in public profile. 
This should definitely be the case so that individuals can be followed right after creation.

**Comment by pgoellnitz** [comment]
These individuals seem to have been excluded deliberately as it would produce quite some entries without any observations in the public profiles.

Needs clarification how to proceed with this.

**Comment by pgoellnitz** [comment]
In discussion with @daria-sl:
* Individuals without observations must be shown in the profile
* Individuals without observation should be cleansed from the history (and when a new phenoyear is generated)

**Comment by daria-sl** [comment]
test successful: it is possible to follow an empty object from another user in the running year.
not tested: empty objects from past years are not shown anymore. How could this be tested? Do you have an example @pgoellnitz ?

**Comment by pgoellnitz** [comment]
Individuals without observations in a past year would be shown if they exists in the database. Currently there are none as we did not import these from the old app.
In future all individuals without observations will be removed from the previous year when we rollover to the next pheno-year. We still need to implement that logic.

**Comment by daria-sl** [comment]
okay perfect. I assume the implementation of the mentioned logic is part of another issue, right?
