### ISSUE TITLE
handle all login messages [PHAENONET-CLIENT-4X]

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#237]
Handle untranslated authentication failure:

* We have blocked all requests from this device due to unusual activity. Try again later. (auth/too-many-requests).
* Access to this account has been temporarily disabled due to many failed login attempts. You can immediately restore it by resetting your password or you can try again later.

- [ ] translations are ready

**Comment by pgoellnitz** [comment]
auth/too-many-requests:
* FirebaseError: Firebase: We have blocked all requests from this device due to unusual activity. Try again later. (auth/too-many-requests).
auth/network-request-failed: [PHAENONET-CLIENT-8T]
* A network error (such as timeout, interrupted connection or unreachable host) has occurred.

**Comment by pgoellnitz** [comment]
Hi @daria-sl, if users fail to login to often in a short period of time Firebase will temporarily lock the account. We should provide the text fragments in these cases. I saw this happen multiple times in the past.

The two messages above are the ones issued by Firebase. Maybe you can take them as a guiadance - maybe the later one.

**Comment by daria-sl** [comment]
German | French | Italian
-- | -- | --
Der Zugriff auf dieses Konto wurde aufgrund zahlreicher fehlgeschlagener Anmeldeversuche vorübergehend deaktiviert. Sie können es sofort wiederherstellen, indem Sie Ihr Passwort zurücksetzen, oder Sie können es später erneut versuchen. | L'accès à ce compte a été temporairement désactivé en raison de nombreuses connexions non réussies. Vous pouvez le rétablir immédiatement en réinitialisant votre mot de passe ou vous pouvez réessayer plus tard. | L'accesso a questo account è stato temporaneamente disabilitato a causa di molti tentativi di login falliti. Puoi ripristinarlo immediatamente reimpostando la password o puoi riprovare più tardi.

**Comment by pgoellnitz** [comment]
Hi @daria-sl, same as in #240: I would need a title for the toast.

The messages seem to be pretty long to be displayed in a toast - but maybe better than nothing?

**Comment by daria-sl** [comment]
@pgoellnitz see #240 for title. Here goes a new proposition for a shorter toast (at least a little shorter^^):

German | French | Italian
-- | -- | --
Zu viele fehlgeschlagene Anmeldeversuche: Ihr Konto wurde vorübergehend deaktiviert. Bitte setzen Sie Ihr Kennwort zrück oder versuchen Sie es später erneut. | Trop de tentatives de connexion échouées : Votre compte a été temporairement désactivé. Veuillez réinitialiser votre mot de passe ou réessayer plus tard. | Troppi tentativi di accesso falliti: questo account è stato temporaneamente disabilitato. Si prega di reimpostare la password o di riprovare più tardi.
