### ISSUE TITLE
add toast for network error [PHAENONET-CLIENT-8T/PHAENONET-CLIENT-8S]

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#240]
Add text for `auth/network-request-failed.*`

- [ ] translation added to issue

**Comment by pgoellnitz** [comment]
Hi @daria-sl, 
another error that we currently do not handle and would need translations. It's thrown if a connection problem occurs while trying to log into the app.

* Error: A network error (such as timeout, interrupted connection or unreachable host) has occurred.

Alternatively I could always just use the English messages if translating these is too much effort.

**Comment by daria-sl** [comment]
@pgoellnitz I would propose to keep it short and more simple. What do you think of this proposition?

German | French | Italian
-- | -- | --
Es ist ein Netzwerkfehler aufgetreten. | Une erreur de réseau est survenue. | Si è verificato un errore di rete.

**Comment by pgoellnitz** [comment]
Hi @daria-sl, sound good to me. But sorry, I forgot to mention that these toast always have a `title` and a `message`. I would use what you postet as the message. 

Could you provide the title also please. I don't know if we have a generic one that we could use?

**Comment by daria-sl** [comment]
@pgoellnitz no problem. I would propose to take the following titles for all errors:
German - French - Italian:
_Fehler - Erreur - Errore_
