### ISSUE TITLE
Logo leads to PhaenoNet.ch

### ISSUE THREAD

**Issue by EstMed** [globe-swiss/phaenonet-client#267]
The PhaenoNet-Logo leads back to the PhaenoNet-Homepage in the respective language.

**Comment by pgoellnitz** [comment]
Link the main page `https://phaenonet.ch/{language}/`. Language is one of `de`, `fr`, `it`.

**Comment by pgoellnitz** [comment]
link should be opened in a new tab.

**Comment by EstMed** [comment]
👍 Lets see how this works with the users.
