### ISSUE TITLE
Species Dropdown Menu not available for new object wih Mac Big Sur

### ISSUE THREAD

**Issue by EstMed** [globe-swiss/phaenonet-client#273]
When creating a new object it is not possible to enter a species because the dropdown menu is not shown. It was a Mac with Big Sur version.

![Dropdown menu](https://user-images.githubusercontent.com/94954045/152141152-83f1b820-96c4-4ec5-b829-622d9ff52d5d.jpg)

**Comment by pgoellnitz** [comment]
@EstMed is the issue reproducible? 

If yes, which browser ans version were you using.

**Comment by pgoellnitz** [comment]
@EstMed, never mind. I could reproduce the issue.

It's a temporary issue occurring after registering while the public profile was not yet created by the backend.
We have a similar issue when navigating to the profile page.

Probably easy to fix both as long as we always have a default user role (phenonet, ranger, wald, ...) that we can fall back to after registering.

**Comment by pgoellnitz** [comment]
The bug with the dropdown selection is fixed. 

The other race conditions are not fixed so easily. Maybe it would make sense to add some comment to try later to the error page.
