### ISSUE TITLE
Language setting in profile is not displayed correctly

### ISSUE THREAD

**Issue by daria-sl** [globe-swiss/phaenonet-client#29]
Sometimes, when the app is, e.g., shown in German and I want to change it to French, the following happens: I click on "edit profile" and there, "Français" is shown as selected option (which is not true because the whole app is shown in German). If I now want to change the app language to French, I have to first choose another language than French in the dropdown and then again click on the dropdown menu to select French - only this time it is actually accepted and the app language is changed.

Desired solution: the correct language is shown as selected in the "profile" and "edit profile" screens, so I can change the language by just selecting my desired language in the dropdown on the "edit profile" screen.

**Comment by daria-sl** [comment]
There is yet another problem, maybe this is the reason for the bug mentioned above: When the app is shown in German and I go to "edit profile", then set the language to, e.g. French, and then click "CANCEL", the app stays in French (instead of going back to German), but in my profile view, it says that I chose German as a language...

**Comment by pgoellnitz** [comment]
The whole profile section should not be based on the session data. Also for nickname validation, etc.

**Comment by pgoellnitz** [comment]
Somehow it seems to me that this problem was resolved when upgrading angular in #41.

@daria-sl, can you please check if you still can reproduce this behavior.

**Comment by daria-sl** [comment]
@pgoellnitz yes everything works out perfectly now :) Thank you angular ;-) (and Philippe)

**Comment by pgoellnitz** [comment]
Reopen, identified the issue to happen when the language is changed but not saved in the form.

**Comment by pgoellnitz** [comment]
language settings not loaded from firestore

**Comment by pgoellnitz** [comment]
- [ ] set language on login
- [ ] remove setting lang field on registration
