### ISSUE TITLE
Adapt icons on map for species according to the language

### ISSUE THREAD

**Issue by daria-sl** [globe-swiss/phaenonet-client#31]
New icons should contain the following two letters for the three languages (up to now, only German species names are used to produce these abbreviations). Also, two German abbreviations should be changed for uniformity reasons.

Species | abbreviation de | Fr | It
-- | -- | -- | --
Bergahorn | Ba | Es | Am
Rotbuche | Rb (alt: Bu) | He | Fa
Edelkastanie | Ek | Ch | Ca
Fichte | Fi | Ec | Ar
Flieder | Fl | Li | Se
Hängebirke | Hb | Bp | Bb
Hasel | Hs | No | No
Huflattich | Hl   (alt: Hu) | Tu | Ff
Lärche | La | Me | La
Rosskastanie | Rk | Ma | Ic
Schwarzdorn | Sd | En | Pr
Sommerlinde | Sl | Tg | Tn
Winterlinde | Sl | Tp | Ts
Weisstanne | Wt | Sb | Ab
Buschwindröschen | Br | Ab | An

**Comment by pgoellnitz** [comment]
@daria-sl, we would need the updated icon set for all languages. Filenames should stay the same, also for the German icons.

**Comment by daria-sl** [comment]
@pgoellnitz okay, I will check with Dani. Could you tell me what the filenames are in German? Also I'd need to know the size (px) of the images so I could save them correctly. Thanks =)

**Comment by pgoellnitz** [comment]
You can find all current pins here: https://github.com/globe-swiss/phaenonet-client/tree/master/src/assets/img/map_pins

**Comment by daria-sl** [comment]
I received the files from Dani and hope I will be able to handle Adobe XD ;-) just to double check: the file names for the German icon (e.g. hazel tree beginning of flowering) should be identical to the file name for the Italian icon of the same tree/phase, right? So I will save the images into a separate folder per language, ok?

**Comment by pgoellnitz** [comment]
sounds good. thanks.

**Comment by daria-sl** [comment]
Missing species' new lables (German - French - Italian)

Robinie: Ro - Ro - Ro
Roter Holunder: Rh - Sr - Sr
Schwarzer Holunder: Sh - Sn - Sn
Vogelbeere: Vb - So - Su
Gewöhnlicher Löwenzahn: Gl - Po - Tc
Wiesenschaumkraut: Ws - Cp - Bp

**Comment by daria-sl** [comment]
@pgoellnitz : the new files are available at [https://www.dropbox.com/sh/g6pizeexqj8vyjo/AAC9IH-Zxan3gHVGVXoiW3lLa?dl=0](url)

In the German folder, only the new or updated icons are saved (the other German icons stay the same). I hope the format and naming is correct like this.

**Comment by daria-sl** [comment]
The test was successful, thank you very much! In French, I realized that we should rename the following species so it matches the abbreviation we use:

old: Bouleau / new: Bouleau pendant

Maybe in the same run you could fix issue https://github.com/globe-swiss/phaenonet-client/issues/105 that I just created (if these two things go together well).
