### ISSUE TITLE
Add new species for PhenoWald

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#310]
Configure the new plant species for the wald.

Information needed:
(see example: https://github.com/globe-swiss/phaenonet-client/issues/198)
- [x] describe species and phenophases
- [x] translate all new text ([current translations](https://github.com/globe-swiss/phaenonet-client/blob/master/src/assets/i18n/fr-CH.json))
- [x] validate wording with WSL 

Implementation:
- [x] add species configuration
- [x] add translations
- [x] validate configuration by WSL

**Comment by EstMed** [comment]
No new translations needed for phenophases.

**Comment by pgoellnitz** [comment]
Hi @EstMed, 
could you please provide the translations for _Gemeine Esche_.

**Comment by EstMed** [comment]
[Fraxinus.xlsx](https://github.com/globe-swiss/phaenonet-client/files/8521595/Fraxinus.xlsx)

Aus drei Knospen haben sich die ersten Blätter entfaltet | Premières feuilles sont déployées sur 3 bourgeons | Da tre gemme si sono sviluppate le prime foglie

50% der Blätter des Baumes sind entfaltet | 50 % des feuilles de l'arbre sont déployées | Il 50% delle foglie sull'albero si è sviluppato

Die Blüten von drei Blütenknospen im Baum sind geöffnet | Les premières fleurs sont ouvertes en 3 points différents de l'arbre | Primi fiori aperti in tre punti diversi dell'albero

50% der Blüten offen oder schon verblüht | 50 % des fleurs sont ouvertes ou déjà fanées | Il 50% die fiori sono aperti o sfioriti

50% der sommerlichen Blattfläche ist abgefallen | 50 % du feuillage estival de l'arbre est tombé | Il 50% della superficie fogliare è caduto

**Comment by EstMed** [comment]
Gemeine Esche
Frêne commun
Frassino comune
