### ISSUE TITLE
adapt station view for PhenoWald

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#319]
Adapt frontend for Phenowald.

- [x] add source
- [x] consider tree identifiers in observation grouping per site/station
- [x] add translations
- [x] add assets

open:
- [x] provide map pin assets @EstMed

**Comment by pgoellnitz** [comment]
@EstMed, could you please add the PhenoWald map icon to the ticket? Thanks!

**Comment by pgoellnitz** [comment]
first preview without assets: https://phaenonet-test--refs-heads-319-phenowald-1malagfq.web.app/map

**Comment by EstMed** [comment]
![map_pin_wsl](https://user-images.githubusercontent.com/94954045/164708698-07cd558e-495e-4c24-b41b-b962ffe06b23.svg)
![map_pin_wsl_2](https://user-images.githubusercontent.com/94954045/164708705-80d38b2a-ddf9-45be-ae3c-d9d2b5e86829.svg)

**Comment by pgoellnitz** [comment]
closes #275

**Comment by pgoellnitz** [comment]
Hi @EstMed, unfortunately the svg image as provided is not safe for web. Would it be possible to provide it as .png file?

I tried to convert it myself but with "free tooling" it didn't seem to look right after conversion.

**Comment by EstMed** [comment]
.png wird von Github nicht unterstützt, deswegen auf diesem Weg.
lg

Esther Meduna
Wissenschaftliche Mitarbeiterin

***@***.***

Verein GLOBE Schweiz
Monbijoustrasse 40
3003 Bern

Tel.: +41 78 722 91 23
E-Mail: ***@***.******@***.***>
Web: www.globe-swiss.ch<http://www.globe-swiss.ch/> | www.phaenonet.ch<http://www.phaenonet.ch/>

Von: Philippe Göllnitz ***@***.***>
Gesendet: Freitag, 13. Mai 2022 09:58
An: globe-swiss/phaenonet-client ***@***.***>
Cc: Esther Meduna ***@***.***>; Mention ***@***.***>
Betreff: Re: [globe-swiss/phaenonet-client] adapt station view for PhenoWald (Issue #319)


Hi @EstMed<https://github.com/EstMed>, unfortunately the svg image as provided is not safe for web. Would it be possible to provide it as .png file?

I tried to convert it myself but with "free tooling" it didn't seem to look right after conversion.

**Comment by pgoellnitz** [comment]
![map_pin_wsl](https://user-images.githubusercontent.com/17765935/169505480-7c530827-2e02-4d04-a21f-d3a9af234026.png)
