### ISSUE TITLE
Copy link to profile does not work on Safari browser (Mac Laptop and IPhone)

### ISSUE THREAD

**Issue by daria-sl** [globe-swiss/phaenonet-client#46]
When opening the App (both test and real App) on Safari browser and clicking on the link symbol next to the profile name, nothing happens (no pop-up is appearing and pressing PASTE somewhere does not result in anything). However, on other browsers and devices, the function works fine (e.g. Windows Laptop with Firefox, Samsung Mobile Phone, Mac Laptop with Chrome Browser all work well).

**Comment by pgoellnitz** [comment]
@daria-sl, the link should now copy on all browsers. Please check on [phaenonet-test](https://phaenonet-test.web.app/).

**Comment by daria-sl** [comment]
Thank you, it worked on my IPhone now =) I can't check on Safari and Mac, though, because I don't have such a device. Did it work on your laptop? From my point of view, we can put this on the production environment. Then I ll tell Linda we fixed it =)
