### ISSUE TITLE
Show more button should not be shown when there are no entries

### ISSUE THREAD

**Issue by daria-sl** [globe-swiss/phaenonet-client#56]
A) empty public profile of someone I got the link from:
![image](https://user-images.githubusercontent.com/65400300/92923709-27205e00-f438-11ea-823c-8bff8161ef0e.png)

"Mehr anzeigen" should not be shown; instead new text (tbd @daria-sl)

B) my own profile:
![image](https://user-images.githubusercontent.com/65400300/92923801-4ae3a400-f438-11ea-85b7-72557383ec2e.png)

"Mehr anzeigen" should not be shown for observations; instead new text (tbd @daria-sl)
"Mehr anzeigen" and "should not be shown if there are no activities yet, instead new text (tbd @daria-sl)

**Comment by daria-sl** [comment]
@pgoellnitz would you agree to print the texts "noch keine Beobachtungen" / "noch keine Aktivitäten"? If yes, I would get the translations for these two "sentences". And then we will have to think about the layout/placement of these new phrases...

**Comment by pgoellnitz** [comment]
obsolete as the concept of showing objects in the profile has changed.
