### ISSUE TITLE
Improve "empty page"

### ISSUE THREAD

**Issue by daria-sl** [globe-swiss/phaenonet-client#57]
Design and install page which is to be shown if, e.g., an empty object is chosen (I clicked on the activity of another user, but in the meantime, this user has deleted the object). 

![image](https://user-images.githubusercontent.com/65400300/92924543-6c915b00-f439-11ea-83d0-9e5115438269.png)

@pgoellnitz I don t think this is urgent, but it is something you also proposed to do. Do you know which "cases" of "strange empty pages" we've got? I think this would be something that Dani should design for us, but he would need to know in which cases the empty page could be accessed by users in order to design it appropriately.

**Comment by pgoellnitz** [comment]
Hi @daria-sl, it happens in two situations (that I know of)
* Manually navigating to the profile page while not being logged in
* Corruped link between login and profile data when restoring backups (or copying data between environments)

I would suggest to handle the first one by redirecting to the login page.
The second actually should be logged as an error. However we still do send client side failures to the cloud to be aware of them. see #45

**Comment by pgoellnitz** [comment]
also relates to #11.

**Comment by daria-sl** [comment]
Hello, thank you for your replies and sorry I didn't answer before. 

- Handling the empty page if a user manually navigates to the profile page while not being logged in by redirecting him to the login page is perfect for me, you can "install" it that way =)

- for the second case you describe (corrupted link between login and profile data when restoring backups or copying data between environments) I do not quite understand to be honest. You say it should be logged as an error (which is fine by me) but what happens on the frontend for the user? Do we need to design an "error page" for this case?

- There is a third case with an empty page, as I described it in the first comment: if I click on an activity of another user, but his object has been deleted in the meantime. Do you have a solution ready for this case as well and/or do we need to design an "error page" in this case?

**Comment by daria-sl** [comment]
hi @pgoellnitz do you need anything more from my side concerning these empty/error pages? If so, just put another comment below, if not, I'm assuming that everything is fine =)
