### ISSUE TITLE
Change Basemap in Profile

### ISSUE THREAD

**Issue by EricWyss64** [globe-swiss/phaenonet-client#621]
![Image](https://github.com/user-attachments/assets/ab0f9c7c-6a53-482c-9df9-d478f598aa0e)
Im Profil bzw. in der Datenerfassung ist noch die alte Basemap. Hier die schwarz/weiss Map mit Relief einfügen.

**Comment by pgoellnitz** [comment]
follow-up to #614, was overlooked there.
