### ISSUE TITLE
Manage followings of individuals and users

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#72]
![image](https://user-images.githubusercontent.com/17765935/106643292-ce3d9780-6589-11eb-8803-68dea0c31747.png)

- [x] display followed individuals
- [x] display followed users
- [x] correct types for meteoswiss stations #126
- [x] process individual counters on create/delete
- [-] ~~initialize individual counters values~~
- [-] ~~reset counters on phenoyear rollover~~
- [ ] translations

**Comment by pgoellnitz** [comment]
relates to #95

**Comment by pgoellnitz** [comment]
@daria-sl, we would need translations for:
* Person
* ABONNEMENTE

thanks

**Comment by daria-sl** [comment]
ITALIENISCH:
Persona
Sottoscrizioni

FRANZÖSISCH:
Personne
Abonnements

Daria Lehmann
Wissenschaftliche Mitarbeiterin

[cid:image001.png@01D706A7.86B653C0]

Verein GLOBE Schweiz
Papiermühlestrasse 172
3003 Bern

Tel.: +41 58 484 96 41<tel:+41%2058%20484%2096%2041>
E-Mail: dlehmann@globe-swiss.ch<mailto:dlehmann@globe-swiss.ch>
Web: www.globe-swiss.ch<http://www.globe-swiss.ch/> | www.phaenonet.ch<http://www.phaenonet.ch/>

Von: Philippe Göllnitz <notifications@github.com>
Gesendet: Freitag, 19. Februar 2021 10:07
An: globe-swiss/phaenonet-client <phaenonet-client@noreply.github.com>
Cc: Daria Lehmann <dlehmann@globe-swiss.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [globe-swiss/phaenonet-client] Manage followings of individuals and users (#72)


@daria-sl<https://github.com/daria-sl>, we would need translations for:

  *   Person
  *   ABONNEMENTE

thanks

**Comment by pgoellnitz** [comment]
@daria-sl, final test?

**Comment by daria-sl** [comment]
Successful! 👍
