### ISSUE TITLE
Invites part I: Create invite and automatic follow function

### ISSUE THREAD

**Issue by daria-sl** [globe-swiss/phaenonet-client#95]
- screendesigns from Dani tbd
- users can invite other users to phaenonet
- they see who they invited and if they accepted the invitation; if yes, automatic following is enabled and the profile of the new user can be viewed
- invitations can be resent
- invitations can be removed from list (both if accepted and if not accepted)
- if someone is invited who is already registered, this person is added to the list and automatic following is enabled
- invited users can also be "unfollowed" directly in the list

**Comment by daria-sl** [comment]
Designs by Dani are now stored in Dropbox: https://www.dropbox.com/sh/p5fib8vy6fdvkaf/AADkOJCcMc1lzb8Nv0XKjTsxa?dl=0

**Comment by pgoellnitz** [comment]
@daria-sl, do you think it is a good idea to allow free text in the invite. For sure it makes it more personal but also opens up the process to spam. 
We probably sanitize the content but you would not be in control what is sent out with the PhaenoNet mail address. (Except if you want to add a manual validation step)

**Comment by daria-sl** [comment]
Proposition for a standard e-mail that someone would get from Peter who invited him/her:

DEUTSCH | FRANZ | ITAL
-- | -- | --
Hallo | Bonjour | Buongiorno
[Username Peter] ([Usermail Peter]) lädt Sie ein, bei PhaenoNet mitzumachen. Klicken Sie auf folgenden Link, um sich zu registrieren: xxx | [Username Peter] ([Usermail Peter]) vous invite à participer à PhaenoNet. Veuillez cliquer sur le lien suivant pour vous inscrire : xxx | [Username Peter] ([Usermail Peter]) vi invita a partecipare a PhaenoNet. Cliccare sul seguente link per registrarsi : xxx
Bei Fragen wenden Sie sich bitte an info@phaenonet.ch. | Pour toute question, veuillez contacter info@phaenonet.ch. | Se avete domande, per favore contattate info@phaenonet.ch.
Freundliche Grüsse | Meilleures salutations | Cordiali saluti
Das PhaenoNet Team | PhaenoNet team | Il team di PhaenoNet

**Comment by pgoellnitz** [comment]
open points:
- [ ] "hand-pointer" shown also on image for registered invites
- [ ] "hand-pointer' only on "erneut senden" text (and button)
- [ ] change text + i18n
- [ ] remove "back to profile" button
- [ ] add html mail + i18n
- [ ] send mails

**Comment by daria-sl** [comment]
Follow-up Issues:
https://github.com/globe-swiss/phaenonet-client/issues/145
https://github.com/globe-swiss/phaenonet-client/issues/146

**Comment by daria-sl** [comment]
Hello, for the texts (except emails) please see table below.


<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/DARIAG~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/DARIAG~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/DARIAG~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=DE-CH style='tab-interval:35.4pt;word-wrap:break-word'>




Deutsch   alt (nur angegeben, falls Änderung gewünscht) | Deutsch | Französisch | Italienisch
-- | -- | -- | --
  | Einladungen | Invitations | Inviti
  | Einladung für | Invitation   pour | Invito per
Noch nicht   gesendet | Wird gesendet… | Envoi… | Invio…
  | Versendet am | Envoyé le | Inviato il
  | Erneut senden | Renvoyer | Invia di   nuovo
Registriert   am | registriert am | inscrit le | registrato il
  | Jetzt   einladen | Inviter   maintenant | Invita ora
  | PERSON   EINLADEN | INVITER UNE   PERSONNE | INVITA UNA   PERSONA
  | Mailadresse | Courriel | E-mail
Speichern | Einladung senden | Envoyer l’invitation | Inviare l’invito
[Warnung,   falls unter 10’ erneut gesendet] | Erneutes Senden noch nicht möglich   Einladungen können höchstens alle 10   Minuten erneut gesendet werden. | Renvoi pas encore possible   Les invitations peuvent être   renvoyées au maximum toutes les 10 minutes. | Reinvio non ancora possibile   Gli inviti possono essere reinviati al   massimo ogni 10 minuti.




</body>

</html>

**Comment by pgoellnitz** [comment]
@daria-sl: I think the translation for 'MEINE EINLADUNGEN' is the only one still missing.

**Comment by daria-sl** [comment]
Thank you for your work @pgoellnitz ! Pretty cool =)

- when someone accepts the invitation, auto-follow does not work anymore
- if I click on "register now" in the mail in mailtrap.io, I get redirected to the registration page (which is correct), but then without me doing anything else, I get the message "you have been registered successfully" and then I get redirected to the map view, but I am not logged in and I do not know my access data. Is this only a problem within mailtrap or is this something we should fix?
- rest seems to work all good :) (I only tested the invite-functionality and not everything else in the app..)

**Comment by pgoellnitz** [comment]
Hi @daria-sl, 

- auto-follow should now work
- in the mail the url is directly pointing to the registration page. If you are already logged in it redirects to the map (with an confusing message that you were "registered successfully"). That's the current behaviour but can definitely be improved if we want.

**Comment by daria-sl** [comment]
perfect, so I'd say let's launch it =) for the "confusing message" I'll open up a new issue.
